/* Synthetic design preview. No backend calls, credentials or operational records. */
(() => {
  'use strict';
  const data = window.SENTINEL_DATA;
  const app = document.getElementById('app');
  if (!data) { app.innerHTML = '<p class="startup">Preview data could not load. Refresh this page.</p>'; return; }
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths = {
    home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',
    report:'M7 3h8l4 4v14H5V3h2m8 0v5h5M8 12h8M8 16h6',
    form:'M5 3h14v18H5zM8 7h8M8 11h8M8 15h4',
    training:'M3 5h7l2 2 2-2h7v14h-7l-2 2-2-2H3zM12 7v14',
    shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6zM8 12l3 3 5-6',
    law:'M12 3v18M6 21h12M3 7h18M6 7 2 14h8L6 7m12 0-4 7h8l-4-7',
    operations:'M9 3h6l1 4 4 1v8l-4 1-1 4H9l-1-4-4-1V8l4-1zM9 12a3 3 0 1 0 6 0 3 3 0 1 0-6 0',
    people:'M8 11a3 3 0 1 0 0-6 3 3 0 1 0 0 6m8-1a3 3 0 1 0 0-6 3 3 0 1 0 0 6M2 21v-4c0-5 12-5 12 0v4M16 14c5 0 6 2 6 6',
    chart:'M3 21h19M5 18v-6h3v6m3 0V7h3v11m3 0V3h3v15',
    car:'m3 9 3-5h12l3 5v9H3zM3 9h18M6 13h2m8 0h2M5 18v3m14-3v3',
    search:'M10 3a7 7 0 1 0 0 14 7 7 0 1 0 0-14m5 12 6 6',
    check:'m4 12 5 5L20 5',
    clock:'M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18m0 4v6l4 2',
    play:'m7 3 14 9-14 9z',
    grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z',
    box:'m3 7 9-5 9 5v11l-9 4-9-4zm0 0 9 5 9-5m-9 5v10',
    notice:'M12 3 2 21h20zm0 6v5m0 3v1',
    menu:'M3 6h18M3 12h18M3 18h18',
  };
  const icon = (name='report') => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.report}"/></svg>`;
  const crest = () => '<svg class="crest" viewBox="0 0 70 90" role="img" aria-label="Sentinel preview shield"><path fill="#091a27" stroke="#bb9c59" stroke-width="3" d="M35 3 5 13l3 40c2 15 27 34 27 34s25-19 27-34l3-40Z"/><path fill="#15424c" stroke="#859486" d="M35 13 15 20l2 32c2 10 18 24 18 24s16-14 18-24l2-32Z"/><circle cx="35" cy="43" r="15" fill="#102a32" stroke="#c6a55d"/><path d="m35 29 4 9 10 1-8 7 2 10-8-5-8 5 2-10-8-7 10-1Z" fill="#c6a55d"/><text x="35" y="24" text-anchor="middle" fill="#e2c581" font-size="6" font-family="Arial">SENTINEL</text></svg>';
  const moduleByKey = key => data.modules.find(m => m.key === key);
  const titles = {dashboard:'Home',incident_reporting:'Reports',mobile_reporting:'Mobile Reporting',report_inspector:'Report Inspector',cleo:'CLEO Reporting',accident_reconstruction:'Accident Reconstruction',forms:'Forms Library',call_type_rules:'Call Type Paperwork Manager',policy_search:'Law & Reference',orders:'Orders & Memoranda',handbook:'Officer Handbook',paperwork_guide:'Paperwork Guide',training:'Training',qualifications:'Qualifications',fto:'FTO Center',scenario_lab:'Patrol Scenario Simulator',bodycam:'Bodycam & Media',bolo:'BOLO',watch_commander:'Watch Commander',assistant_operations:'Assistant Operations',armory:'Armory',rfi:'RFI',truck_gate:'Truck Gate',vehicle_inspections:'Vehicle Inspections',personnel:'Personnel',performance:'Performance Evaluation',stats:'Statistics & Activity',analytics:'Department Analytics',announcements:'Announcements',ai_assistant:'Sentinel Assistant',data_exchange:'Data Exchange',administration:'Administration',builder:'Builder / System Controller',dor:'Daily Observation Report (DOR)',action:'Action Center',modules:'All Modules',operations:'Operations',welcome:'Welcome',forms_manager:'Forms Manager',account:'Account & Identity'};
  const nav = [['dashboard','Home','home'],['incident_reporting','Reports','report'],['forms','Forms','form'],['training','Training','training'],['fto','FTO Center','shield'],['policy_search','Law & Reference','law'],['operations','Operations','operations'],['personnel','Personnel','people'],['analytics','Analytics','chart']];
  const families = {
    incident_reporting:['incident_reporting','mobile_reporting','report_inspector','cleo','accident_reconstruction'],
    forms:['forms','forms_manager','call_type_rules','paperwork_guide'],
    training:['training','qualifications','scenario_lab'],
    fto:['fto','dor'],
    policy_search:['policy_search','orders','handbook'],
    operations:['watch_commander','assistant_operations','bodycam','bolo','armory','rfi','truck_gate','vehicle_inspections'],
    personnel:['personnel','performance'],analytics:['analytics','stats'],
    administration:['administration','builder','data_exchange','ai_assistant','account'],
  };
  const groupFor = key => Object.keys(families).find(group => families[group].includes(key)) || key;
  const glyphFor = key => nav.find(n=>n[0]===groupFor(key))?.[2] || 'grid';
  let state = {records:{},details:{},ratings:{},dorComments:'',scenarioStarted:false,scenarioLog:[]};
  try { const saved=JSON.parse(sessionStorage.getItem('sentinel-design-v2') || 'null'); if(saved && saved.records && saved.ratings && Array.isArray(saved.scenarioLog)) state={...state,...saved}; } catch (_) {}
  function save(){try{sessionStorage.setItem('sentinel-design-v2',JSON.stringify(state));}catch(_){toast('Changes remain in this page; browser session storage is unavailable.');}}
  let toastTimer;
  function toast(message){const target=document.getElementById('toast');target.textContent=message;target.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>target.classList.remove('show'),4200);}
  const link=(key,label,cls='tab')=>`<a class="${cls}" href="#${esc(key)}">${esc(label || titles[key] || key)}</a>`;
  const tag=(label,color='')=>`<span class="badge ${color}">${esc(label)}</span>`;
  const button=(action,label,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${esc(label)}</button>`;
  const head=(title,subtitle='',actions='')=>`<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${actions || '<span class="preview-note">Synthetic design preview</span>'}</div>`;
  const panel=(title,content,extra='')=>`<article class="panel ${extra}"><h2>${title}</h2>${content}</article>`;
  const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const metric=(label,value,name='report',color='')=>`<article class="metric"><div class="metric-icon ${color}">${icon(name)}</div><div><div class="metric-label">${esc(label)}</div><strong>${esc(value)}</strong></div></article>`;
  const ring=(value,label,color='#36c965')=>`<div class="ring-wrap"><div class="ring" style="--value:${value};--color:${color}"><strong>${value}%</strong></div>${esc(label)}</div>`;
  const activity=(name,detail,type='report',color='')=>`<div class="activity"><span class="activity-dot ${color}">${icon(type)}</span><div><strong>${esc(name)}</strong><small>${esc(detail)}</small></div></div>`;
  function tabs(key,items,current){return `<div class="subnav">${items.map(([id,label])=>`<a class="tab ${current===id?'active':''}" href="#${key}/${id}">${esc(label)}</a>`).join('')}</div>`;}
  function familyNav(key){const group=groupFor(key),items=families[group];return items?`<div class="subnav">${items.map(id=>`<a class="tab ${id===key?'active':''}" href="#${id}">${esc(titles[id])}</a>`).join('')}</div>`:'';}
  function moduleCards(keys){return `<div class="module-grid">${keys.map(key=>{const m=moduleByKey(key);return `<a href="#${key}" class="module-card" data-module="${key}">${icon(glyphFor(key))}<h2>${esc(titles[key] || m?.name)}</h2><p>${esc(m?.capabilities.slice(0,3).join(' · ') || 'Controlled configuration and review tools')}</p>${tag('Open workspace')}</a>`;}).join('')}</div>`;}
  function scopePanel(key){const m=moduleByKey(key==='forms_manager'?'forms':key);return m?`<details class="panel" style="margin-top:16px"><summary>Original capabilities preserved (${m.capabilities.length})</summary><ul class="capabilities">${m.capabilities.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p class="source-meta">Scope reference. Controls in this preview demonstrate layout and synthetic records; connected workflows are still being built.</p></details>`:'';}
  const reportTypes=[['Traffic Stop','Traffic citation & warning','car'],['Crash Report','Traffic collision','car'],['Incident Report','General incident','report'],['Theft / Larceny','Property crime','box'],['Assault / Battery','Person offense','people'],['Domestic','Domestic-related incident','home'],['DUI / OWI','Impaired driving','car'],['Juvenile','Juvenile-related incident','people'],['Property','Property & evidence','box'],['Welfare Check','Check on welfare','shield'],['Field Interview','Document contact','report'],['Other','All other call types','grid']];
  const seeds={
    incident_reporting:[['TEST-0042','Traffic Stop','Demo Officer One','Draft'],['TEST-0041','Incident Report','Demo Officer Two','Submitted'],['TEST-0040','Welfare Check','Demo Officer One','Reviewed']],
    training:[['TRN-101','Evidence handling workshop','Training Team','Scheduled'],['TRN-102','Emergency vehicle operations','Demo Officer One','Completed']],
    qualifications:[['QUAL-001','First aid / CPR','Demo Officer One','Current'],['QUAL-002','Annual qualification','Demo Officer Two','Due soon']],
    forms:[['FRM-001','Witness statement — sample','Forms Library','Blank'],['FRM-002','Incident supplement — sample','Forms Library','Blank'],['FRM-003','Vehicle inspection — sample','Forms Library','Blank']],
    orders:[['SRC-001','Sample patrol procedures','Training corpus','Sample'],['SRC-002','Sample memorandum','Training corpus','Sample']],
    bolo:[['BOLO-TEST-01','Training vehicle bulletin','Demo Watch Alpha','Active'],['BOLO-TEST-02','Training property bulletin','Demo Watch Bravo','Located']],
    armory:[['ASSET-TEST-01','Training equipment kit','Demo Officer One','Checked out'],['ASSET-TEST-02','Inert training device','Armory Team','Available']],
    rfi:[['RFI-TEST-01','Inert equipment issue','Demo Officer One','Issued'],['RFI-TEST-02','Training inventory return','RFI Team','Returned']],
    truck_gate:[['GATE-TEST-01','Synthetic delivery vehicle','Demo Company A','On site'],['GATE-TEST-02','Synthetic service vehicle','Demo Company B','Exited']],
    personnel:[['PERSON-TEST-01','Demo Officer One','Demo Watch Alpha','Active'],['PERSON-TEST-02','Demo Officer Two','Demo Watch Bravo','Pending approval']],
    performance:[['PERF-TEST-01','Annual development review','Demo Officer One','Draft']],
    announcements:[['NOTICE-TEST-01','Training schedule available','Training Team','Published']],
    assistant_operations:[['OPS-TEST-01','Monthly readiness review','Demo Supervisor','In progress'],['OPS-TEST-02','Inspection follow-up','Demo Watch Alpha','Open']],
    bodycam:[['MEDIA-TEST-01','Synthetic training media metadata','Demo Officer One','Metadata only']],
    vehicle_inspections:[['VI-TEST-01','Training vehicle inspection','Demo Officer One','Draft']],
    cleo:[['CLEO-TEST-01','Synthetic structured incident','Demo Officer One','Returned']],
    accident_reconstruction:[['CASE-TEST-01','Training collision reconstruction','Demo Investigator','Draft']],
    stats:[['ACT-TEST-01','Community contacts: 8','Demo Officer One','Recorded']],
    data_exchange:[],ai_assistant:[],
  };
  const getRecords=key=>state.records[key] || seeds[key] || [];
  function recordTable(key,filter=''){const rows=getRecords(key).filter(row=>!filter || row[3].toLowerCase()===filter.toLowerCase());return rows.length?table(['Record','Title / Type','Owner / Team','Status','Actions'],rows.map((r,i)=>[esc(r[0]),esc(r[1]),esc(r[2]),tag(r[3],/completed|current|reviewed|published|active/i.test(r[3])?'green':/draft|returned|due/i.test(r[3])?'gold':''),button('view-record','Open','small',`data-key="${key}" data-id="${esc(r[0])}"`)])):'<div class="empty">No synthetic records in this view.</div>';}
  function dashboard(){return head('Welcome, Demo Supervisor','Department overview · Friday, September 25, 2026')+
    `<div class="metrics">${metric('My Open Tasks','12','form')}${metric('Pending Reviews','5','report','red')}${metric('Overdue Training','3','training','red')}${metric('Active FTO Trainees','4','people','green')}</div>`+
    `<div class="dashboard-grid">${panel('Recent Activity',activity('DOR submitted · Demo Officer One','2 hours ago','form','gold')+activity('Report review completed','4 hours ago','report')+activity('Training assigned · Traffic stops','5 hours ago','training')+activity('New scenario available','1 hour ago','notice','gold'))}${panel('Department Status',`<div class="rings">${ring(87,'Training Compliance','#b9c522')}${ring(92,'Report Quality')}${ring(76,'FTO Progress','#eca72f')}${ring(95,'Form Completion','#9abc2c')}</div>`)}${panel('Quick Access',`<div class="quick-links">${[['incident_reporting','Create Report','report'],['scenario_lab','Start Scenario','play'],['policy_search','Find Policy','search'],['dor','My DORs','form'],['training','View Training','training'],['announcements','Department Notices','notice']].map(([k,l,i])=>`<a href="#${k}">${icon(i)}${l}</a>`).join('')}</div>`)}</div>`+
    `<div class="bottom-grid">${panel('My Work',table(['Priority','Action','Due'],[[tag('High','gold'),link('dor','Review trainee DOR','text-button'),'Today'],[tag('Normal'),link('incident_reporting','Returned report correction','text-button'),'Today'],[tag('Normal'),link('assistant_operations','Readiness review','text-button'),'Tomorrow']]))}${panel('Explore the full department workspace',`<p>All original Portal and Sentinel modules remain available.</p><div class="actions">${link('modules','Browse all 33 modules','primary')}${link('action','Action Center')}</div>`)}</div>`;}
  function reports(tab='new'){return head('Reports','Officer reports and review workflow')+familyNav('incident_reporting')+tabs('incident_reporting',[['new','New Report'],['draft','My Drafts'],['submitted','Submitted'],['reviewed','Reviewed']],tab)+(tab==='new'?`<div class="report-tiles">${reportTypes.map(([name,desc,i])=>`<button class="report-tile" data-action="new-record" data-key="incident_reporting" data-type="${esc(name)}">${icon(i)}<b>${name}</b><small>${desc}</small></button>`).join('')}</div>`:'')+panel(tab==='new'?'Recent Reports':`${titles.incident_reporting} · ${tab}`,recordTable('incident_reporting',tab==='new'?'':tab))+scopePanel('incident_reporting');}
  function inspector(tab='findings'){return head('Report Inspector','Review cues, approved-source context, and authorized human judgment.',button('inspect','Run sample inspection','primary'))+familyNav('report_inspector')+`<div class="metrics">${metric('Completeness cues','2','report')}${metric('Source verification','Pending','law')}${metric('Packet items','5 / 6','form')}${metric('Human review','Required','people','green')}</div>`+tabs('report_inspector',[['findings','Findings'],['sources','Policy References'],['suggestions','Suggestions'],['review','Final Review']],tab)+panel(tab==='sources'?'Source verification':tab==='review'?'Human Judgment':'Sample review findings',tab==='sources'?'<p>No approved operational corpus is connected. This sample cannot establish legal sufficiency or policy compliance.</p>':tab==='review'?'<label class="field">Reviewer notes<textarea placeholder="Synthetic review notes only"></textarea></label><div class="actions">'+button('save-note','Save demo review','primary')+'</div>':[['Clarify location details','Add a specific location or landmarks if supported by the facts.','notice','gold'],['Check witness information','Verify whether contact details were documented. Do not invent missing facts.','people',''],['Verify packet requirements','Compare the selected call type with approved paperwork rules.','form','']].map(([title,desc,i,c])=>`<div class="finding"><span class="activity-dot ${c}">${icon(i)}</span><div><h3>${title}</h3><p>${desc}</p></div>${tag('Automated cue',c)}</div>`).join(''))+scopePanel('report_inspector');}
  function fto(tab='progress'){let content='';
    if(tab==='progress') content=`<div class="two-col">${panel('Training Phase','<h2>Phase 2 — Field Operations</h2><div class="row spread"><span class="muted">Phase completion</span><b>66%</b></div><div class="progress"><i style="width:66%"></i></div><p class="source-meta">Standard program · Week 3 · Synthetic assignment</p><h3 style="margin-top:25px">Phase Requirements</h3>'+[['Vehicle Stops',80,'8 / 10'],['Investigative Stops',63,'5 / 8'],['Report Writing',75,'6 / 8'],['Evidence Handling',67,'4 / 6'],['Court Procedures',50,'2 / 4']].map(([l,v,n])=>`<div class="task-row">${icon('form')}<span>${l}</span><div class="progress"><i style="width:${v}%"></i></div><small>${n}</small></div>`).join(''))}<div>${panel('Recent Evaluations',[['DOR · Vehicle Operations','5.0'],['DOR · Scene Management','4.0'],['Weekly Evaluation','4.5'],['Phase 1 Evaluation','4.0']].map(([l,n])=>`<a href="#dor" class="evaluation-row"><span class="activity-dot">${icon('form')}</span><span>${l}<br><small>Synthetic training record</small></span><b>${n}</b></a>`).join(''))}${panel('My FTO','<div class="row"><span class="avatar">DF</span><div><strong>Demo FTO</strong><p>Primary training officer</p></div></div>','fto-profile')}</div></div>`;
    else if(tab==='taskbook') content=panel('Digital Task Book',table(['Phase','Task','Status'],data.tasks.map(t=>[esc(t.ProgramPhase),esc(t.TaskName),tag('Not started')])));
    else if(tab==='dors') content=panel('Daily Observation Reports',`<p>31 standardized evaluation categories. Trainee acknowledgment means receipt, not agreement.</p><div class="actions">${link('dor','Open DOR','primary')}</div>`);
    else if(tab==='remediation') content=panel('Remediation & Re-evaluation',table(['Deficiency','Assigned trainer','Due','Status'],[['Synthetic documentation exercise','Demo FTO','Next session',tag('Open','gold')]])+button('new-record','Add remedial draft','primary', 'data-key="fto" data-type="Remedial training"'));
    else if(tab==='evaluations') content=panel('Weekly & Phase Evaluations',table(['Evaluation','Program','Status'],[['Week 3 review','Standard 8-week',tag('Draft','gold')],['Phase 1 review','Accelerated 4-week',tag('Sample')]]));
    else content=panel('FTO Resources',`<p>Standard 8-week and accelerated 4-week programs are both retained.</p><div class="actions">${link('handbook','Officer Handbook')}${link('scenario_lab','Scenario Lab')}${link('qualifications','Qualifications')}</div>`);
    return head('FTO Center','Training progress, observation, development and review.')+familyNav('fto')+tabs('fto',[['progress','My Progress'],['taskbook','Task Book'],['dors','DORs'],['evaluations','Evaluations'],['remediation','Remediation'],['resources','Resources']],tab)+content+scopePanel('fto');}
  function dor(tab='categories'){let content='';
    if(tab==='categories') {let group=''; content=data.categories.map(c=>{const newGroup=group!==c.CategoryGroup;group=c.CategoryGroup;const anchor=data.anchors.find(a=>a.CategoryNumber===c.CategoryNumber);return `${newGroup?`<h3 class="rating-group">${esc(group)}</h3>`:''}<div class="rating-row"><details><summary>${esc(c.CategoryNumber)}. ${esc(c.CategoryName)}</summary>${anchor?[['1',anchor.Rating1_Unacceptable],['4',anchor.Rating4_Acceptable],['7',anchor.Rating7_Superior]].map(([n,t])=>`<p><b>${n}:</b> ${esc(t)}</p>`).join(''):''}</details><div class="ratings" role="group" aria-label="${esc(c.CategoryName)}">${['1','2','3','4','5','6','7','N/O'].map(n=>`<button aria-label="${esc(c.CategoryName)}: ${n}" aria-pressed="${state.ratings[c.CategoryNumber]===n}" class="${state.ratings[c.CategoryNumber]===n?'selected':''}" data-rating="${n}" data-category="${c.CategoryNumber}">${n}</button>`).join('')}</div></div>`;}).join('');}
    else if(tab==='tasks') content=table(['Phase','Task'],data.tasks.slice(0,18).map(t=>[esc(t.ProgramPhase),esc(t.TaskName)]));
    else if(tab==='comments') content=`<label class="field">Observation comments · synthetic only<textarea id="dor-comments">${esc(state.dorComments)}</textarea></label>`;
    else content=`<p>${Object.keys(state.ratings).length} of 31 categories rated or marked N/O.</p><div class="notice">Final ratings require an authorized FTO. Trainee acknowledgment records receipt, not agreement. Supervisor review follows acknowledgment.</div>${button('save-dor','Save demo draft','primary')}`;
    return head('Daily Observation Report (DOR)','Digital FTO evaluation · 1–7 rating scale and Not Observed',button('save-dor','Save Draft','primary'))+familyNav('dor')+`<div class="form-grid" style="margin-bottom:15px"><label>Trainee<select><option>Demo Officer One</option><option>Demo Officer Two</option></select></label><label>Date<input type="date" value="2026-09-25"></label><label>Phase<select><option>Phase 2</option><option>Phase 1</option><option>Phase 3</option><option>Phase 4</option></select></label></div>`+tabs('dor',[['categories','Evaluation Categories'],['tasks','Task Book Items'],['comments','Comments'],['review','Final Review']],tab)+panel(tab==='categories'?'Core Competencies (1–7 Rating Scale)':titles.dor,content);}
  function scenario(){return head('Patrol Scenario Simulator','Realistic training scenarios · synthetic environment')+familyNav('scenario_lab')+`<div class="scenario-layout"><article class="scene-frame"><img class="scene-photo" src="assets/patrol-dusk.png" alt="Generated dusk patrol training environment"><div style="padding:14px"><h2>Suspicious vehicle complaint</h2><p>Dispatch: Respond to the training area and acknowledge the call. Additional information is pending.</p></div></article>${panel('Scenario Information',`<div class="scene-data"><div><span>Type</span><b>Patrol response</b></div><div><span>Environment</span><b>Training installation</b></div><div><span>Time</span><b>2100 hours · Dusk</b></div><div><span>Mode</span><b>Evaluation preview</b></div><div><span>Status</span>${tag(state.scenarioStarted?'Active demo':'Ready',state.scenarioStarted?'green':'')}</div></div><div class="actions">${button('begin-scenario',state.scenarioStarted?'Restart demo':'Begin Scenario','primary')}</div>`)}</div>${state.scenarioStarted?`<div class="bottom-grid">${panel('Radio / CAD',`<div id="scenario-log">${state.scenarioLog.map(l=>activity(l,'Recorded in this browser session','report')).join('')}</div><form id="scenario-action"><label class="field">Officer action<input name="action" required maxlength="300" placeholder="Describe your next action using synthetic facts"></label><div class="actions"><button class="primary" type="submit">Record action</button>${link('forms','End call · paperwork')}</div></form><p class="auth-label">This preview records your actions. AI interpretation and scenario consequences are not connected.</p>`)}${panel('Field Notebook','<textarea placeholder="Synthetic field notes"></textarea>')}</div>`:''}`+scopePanel('scenario_lab');}
  function watch(tab='overview'){const detail={personnel:['Demo Officer One','Demo Officer Two','Demo Officer Three'],vehicles:['Training unit 01','Training unit 02'],events:['Training vehicle stop','Readiness inspection'],turnover:['Open reports','Pending training','Items marked STALE — VERIFY'],decisions:['Synthetic review decision']};const content=tab==='overview'?`<div class="watch-grid">${panel('Current Shift','<h2>Bravo Shift</h2><p>09/25/2026<br>1400–2200</p><h3 style="margin-top:22px">Personnel Status</h3>'+[['On duty','12'],['Off duty','3'],['Leave','2'],['Training','1']].map(([k,v])=>`<div class="task-row"><span>${k}</span><b>${v}</b></div>`).join(''))}${panel('Post Assignments',table(['Post','Personnel','Status'],[['Main Gate','2 officers',tag('Active','green')],['Back Gate','2 officers',tag('Active','green')],['MCX','1 officer',tag('Active','green')],['Housing Patrol','2 officers',tag('STALE — VERIFY','gold')],['CID Support','1 officer',tag('Active','green')]]))}${panel('Active Events',activity('Training traffic stop','15 minutes ago','car','gold')+activity('FTO remedial review','Due today','training')+activity('Returned report correction','Pending review','report')+activity('Post verification overdue','STALE — VERIFY','notice','gold'))}</div>`:panel(titles.watch_commander+' · '+tab,table(['Item','Context'],(detail[tab] || []).map(t=>[esc(t),'Synthetic preview']))+`<div class="actions">${button('new-record','Add demo entry','primary',`data-key="watch_commander" data-type="${esc(tab)}"`)}</div>`);return head('Watch Commander','Digital Lieutenant · controlled operational picture',tag('2 items STALE — VERIFY','gold'))+tabs('watch_commander',[['overview','Shift Overview'],['personnel','Personnel'],['vehicles','Posts & Vehicles'],['events','Events'],['turnover','Turnover Brief'],['decisions','Decision Log']],tab)+content+scopePanel('watch_commander');}
  function analytics(tab='training'){const labels={training:['Training Compliance','Report Quality','FTO Progress','Forms Completion'],reports:['Draft Reports','Submitted','Reviewed','Returned'],fto:['Active Trainees','DORs This Week','Phase Reviews','Open Remediation'],operations:['On Duty','Open Due-outs','Inspections','Stale Items'],personnel:['Active Profiles','Pending Approval','Qualifications Due','Annual Reviews']};const values={training:['87%','92%','76%','95%'],reports:['12','8','24','3'],fto:['4','16','2','3'],operations:['12','5','3','2'],personnel:['24','2','3','4']};return head('Department Analytics','Command overview · illustrative synthetic metrics')+tabs('analytics',[['training','Training'],['reports','Reports'],['fto','FTO Program'],['operations','Operations'],['personnel','Personnel']],tab)+`<div class="metrics">${(labels[tab]||labels.training).map((l,i)=>metric(l,(values[tab]||values.training)[i],'chart',i===0?'green':'')).join('')}</div><div class="chart-grid">${panel('Reports by Call Type',`<div class="bar-chart">${[['Traffic',86],['Incident',61],['Theft',45],['Assault',68],['Domestic',51],['Other',37]].map(([l,v])=>`<div><i style="height:${v}%"></i><small>${l}</small></div>`).join('')}</div>`)}${panel('FTO Phase Completion','<div class="pie" role="img" aria-label="Illustrative phase distribution: 30, 26, 24 and 20 percent"></div><div class="legend"><span>Phase 1 · 30%</span><span>Phase 2 · 26%</span><span>Phase 3 · 24%</span><span>Phase 4 · 20%</span></div>')}${panel('Training Status',ring(87,'Training compliance')+'<p class="source-meta" style="text-align:center">Sample figures for design review</p>')}</div>`+`<div class="actions">${link('stats','Statistics & Activity')}</div>`+scopePanel('analytics');}
  function workspace(key,tab='records'){
    const m=moduleByKey(key==='forms_manager'?'forms':key);
    const capabilities=key==='account'?data.accountCapabilities:m?.capabilities || [];
    let content='';
    if(key==='ai_assistant') content=panel('Sentinel Assistant',`<div class="notice">AI is not connected in this design preview.</div><div class="form-grid"><label>Tool<select>${['Narrative Creator','5-W Builder','Order Summary','Policy Search','FTO Coaching','Counseling Draft','Award Recommendation','Annual Training','Smart Forms'].map(v=>`<option>${v}</option>`).join('')}</select></label></div><label class="field" style="margin-top:15px">Synthetic request<textarea placeholder="Describe the assistance you need using synthetic information only"></textarea></label><div class="actions">${button('ai-unavailable','Request assistance','primary')}</div>`);
    else if(key==='policy_search' || key==='orders' || key==='handbook' || key==='paperwork_guide') content=panel(key==='policy_search'?'Controlled Reference Library':titles[key],`<label class="field">Search sample references<input id="record-filter" placeholder="Search titles, sources or versions"></label><div class="subnav" style="margin-top:14px">${['All sources','Georgia law','UCMJ','Federal USC','Base orders'].map(label=>button('source-filter',label,'small')).join('')}</div><div id="record-list">${recordTable('orders')}</div><div class="notice">Sample titles only. No operational legal text or approved-source corpus is connected.</div>`);
    else if(key==='forms_manager' || key==='call_type_rules' || key==='builder' || key==='administration' || key==='account') content=panel(key==='account'?'Identity & Account Management':'Configuration Workspace',`<div class="notice">Design preview. These controls do not change department access, official forms, or environment configuration.</div><div class="module-grid">${(key==='account'?data.accountCapabilities:capabilities).map(c=>`<button class="module-card" data-action="feature-detail" data-feature="${esc(c)}">${icon('operations')}<h3>${esc(c)}</h3>${tag('Preview scope')}</button>`).join('')}</div>`);
    else if(key==='data_exchange') content=panel('Data Exchange',`<p>Export synthetic preview records as JSON. Production imports and other formats remain pending.</p><div class="actions">${button('export','Export preview JSON','primary', 'data-key="all"')}</div>${recordTable(key)}`);
    else content=panel(key==='forms'?'Available Forms':key==='training'?'Training Roster':key==='personnel'?'Department Directory':key==='bodycam'?'Media Library':'Records',`<div class="row spread" style="margin-bottom:12px"><input id="record-filter" aria-label="Search records" placeholder="Search synthetic records"><div class="row">${button('new-record',key==='forms'?'New form draft':'New demo record','primary small',`data-key="${key}"`)}${button('export','Export JSON','small',`data-key="${key}"`)}</div></div><div id="record-list">${recordTable(key)}</div>${key==='bodycam'?'<div class="notice">Media metadata preview. No evidence upload, playback service, transcription or AI connection is active.</div>':''}`);
    return head(titles[key] || m?.name || 'Workspace',key==='forms'?'Find, complete and manage department forms.':'Original Portal workspace · synthetic design preview')+familyNav(key)+content+scopePanel(key);
  }
  function allModules(){return head('All Modules',`${data.modules.length} original Portal and Sentinel modules · nothing removed`)+`<div class="row" style="margin-bottom:16px"><label class="field" style="flex:1">Find a module<input id="module-filter" placeholder="Search by module or capability"></label></div>`+moduleCards(data.modules.map(m=>m.key));}
  function welcome(){return `<main class="welcome"><a class="login-link" href="#dashboard">Open design preview →</a><div class="welcome-content">${crest()}<div><h1>MCPD SENTINEL</h1><p class="motto">TRAIN · DEVELOP · DOCUMENT · PROTECT</p><p class="department">MARINE CORPS POLICE DEPARTMENT</p><div class="signin"><p>Sign in with your department account</p>${button('signin','▦  Sign in with Microsoft','primary')}<small>Authorized personnel only</small><div class="actions" style="justify-content:center">${link('dashboard','Enter synthetic preview','text-button')}</div></div></div></div></main>`;}
  function shell(key,body){const group=groupFor(key);return `<header class="topbar"><button class="mobile-menu" data-action="menu" aria-label="Toggle navigation" aria-expanded="false">${icon('menu')}</button><a class="brand" href="#dashboard">${crest()}<span>MCPD SENTINEL</span></a><div class="top-search">${icon('search')}<input id="global-search" aria-label="Search modules" placeholder="Search reports, policy, training, or personnel…" autocomplete="off"><div id="search-results" class="search-results" hidden></div></div><a class="profile" href="#account" aria-label="Demo Supervisor account"><span class="avatar">DS</span><div><strong>Demo Supervisor</strong><small>Design review · synthetic data</small></div></a></header><aside class="sidebar" id="sidebar"><nav aria-label="Main navigation">${nav.map(([id,label,i])=>`<a class="nav-item ${group===id?'active':''}" href="#${id}">${icon(i)}<span>${label}</span></a>`).join('')}</nav><div class="nav-divider"></div><nav aria-label="More workspaces">${[['action','Action Center','check'],['modules','All Modules','grid'],['administration','Administration','operations']].map(([id,l,i])=>`<a class="nav-item ${key===id||group===id?'active':''}" href="#${id}">${icon(i)}<span>${l}</span></a>`).join('')}</nav><div class="sidebar-bottom"><a class="nav-item" href="#welcome">${icon('shield')}<span>Welcome screen</span></a><div class="sidebar-note">DESIGN PREVIEW<br>FULL ORIGINAL PORTAL SCOPE</div></div></aside><main class="main"><div class="screen" data-screen="${esc(key)}">${body}</div></main>`;}
  function route(){const aliases={home:'dashboard',reports:'incident_reporting',inspector:'report_inspector',policy:'policy_search',scenario:'scenario_lab',watch:'watch_commander',portal:'modules'};const parts=location.hash.slice(1).split('/');let key=aliases[parts[0]] || parts[0] || 'dashboard',tab=parts[1];if(!titles[key])key='dashboard';let body='';
    if(key==='welcome'){app.innerHTML=welcome();return;}
    if(key==='dashboard')body=dashboard();else if(key==='incident_reporting')body=reports(tab);else if(key==='report_inspector')body=inspector(tab);else if(key==='fto')body=fto(tab);else if(key==='dor')body=dor(tab);else if(key==='scenario_lab')body=scenario();else if(key==='watch_commander')body=watch(tab);else if(key==='analytics')body=analytics(tab);else if(key==='modules')body=allModules();else if(key==='operations')body=head('Operations','Department operational tools and command workspaces')+moduleCards(families.operations);else if(key==='action')body=head('Action Center','Required follow-up across your workspace')+panel('Open Actions',table(['Priority','Action','Record','Due'],[[tag('High','gold'),link('dor','DOR supervisor review','text-button'),'Demo Officer One','Today'],[tag('High','gold'),link('incident_reporting','Returned report correction','text-button'),'TEST-0042','Today'],[tag('Normal'),link('fto/remediation','Remedial review','text-button'),'Demo Officer Two','Tomorrow']]));else body=workspace(key,tab);
    app.innerHTML=shell(key,body);document.title=`${titles[key]} · MCPD Sentinel Preview`;window.scrollTo(0,0);
  }
  const dialog=document.getElementById('record-dialog');
  function info(title,message){dialog.innerHTML=`<h2 id="dialog-title">${esc(title)}</h2><p>${esc(message)}</p><div class="actions">${button('close-dialog','Close','primary')}</div>`;dialog.showModal();}
  function newRecord(key,type=''){
    dialog.innerHTML=`<form id="new-record-form" data-key="${esc(key)}"><h2 id="dialog-title">${key==='incident_reporting'?'New Report':'New Demo Record'}</h2><p>Synthetic preview only. This draft stays in this browser session.</p><div class="form-grid"><label>Title / Type<input name="title" required maxlength="100" value="${esc(type)}" placeholder="Synthetic record title"></label><label>Assigned to<input name="owner" required maxlength="80" value="Demo Officer One"></label>${key==='incident_reporting'?'<label>Incident date<input type="date" name="date" value="2026-09-25"></label><label>Location<input name="location" placeholder="Training area"></label><label class="full">Known facts<textarea name="facts" placeholder="Synthetic facts only"></textarea></label>':'<label class="full">Notes<textarea name="notes" placeholder="Synthetic preview notes"></textarea></label>'}</div><div class="actions">${button('close-dialog','Cancel')}<button class="primary" type="submit">Save demo draft</button></div></form>`;dialog.showModal();dialog.querySelector('input')?.focus();
  }
  function exportRecords(key){const payload=JSON.stringify({synthetic:true,previewOnly:true,records:key==='all'?{...seeds,...state.records}:getRecords(key)},null,2);const url=URL.createObjectURL(new Blob([payload],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`sentinel-synthetic-${key}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Synthetic preview JSON exported.');}
  document.addEventListener('click',event=>{
    const rating=event.target.closest('[data-rating]');if(rating){state.ratings[rating.dataset.category]=rating.dataset.rating;rating.closest('.ratings').querySelectorAll('button').forEach(b=>{const selected=b===rating;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});save();return;}
    const target=event.target.closest('[data-action]');if(!target)return;
    const action=target.dataset.action,key=target.dataset.key;
    if(action==='menu'){const open=document.getElementById('sidebar').classList.toggle('open');target.setAttribute('aria-expanded',String(open));}
    else if(action==='close-dialog')dialog.close();
    else if(action==='signin')info('Microsoft sign-in','This is the welcome-screen design preview. Department authentication will use the approved Microsoft environment. Choose “Enter synthetic preview” to review the screens now.');
    else if(action==='new-record')newRecord(key,target.dataset.type || '');
    else if(action==='view-record'){const r=getRecords(key).find(row=>row[0]===target.dataset.id);if(r){const detail=state.details[r[0]];info(r[1],`${r[0]} · ${r[2]} · ${r[3]}. ${detail?Object.entries(detail).map(([field,value])=>`${field}: ${value}`).join(' · '):'Synthetic preview record; no operational record or document is connected.'}`);}}
    else if(action==='save-dor'){state.dorComments=document.getElementById('dor-comments')?.value || state.dorComments;save();toast(`Demo DOR saved in this session: ${Object.keys(state.ratings).length} of 31 categories marked.`);}
    else if(action==='begin-scenario'){state.scenarioStarted=true;state.scenarioLog=['Dispatch: Acknowledge the suspicious vehicle complaint in the training area.'];save();route();}
    else if(action==='export')exportRecords(key);
    else if(action==='ai-unavailable')info('AI connection pending','The preview does not send requests to an AI service. Approved GenAI.mil/STARK endpoint, model and secret connection will be configured in the deployment environment.');
    else if(action==='inspect')info('Sample inspection','The displayed findings are synthetic examples. Live analysis, approved-source retrieval and review routing are not connected in this preview.');
    else if(action==='feature-detail')info(target.dataset.feature,'This original capability remains in scope. This screen previews its placement; the connected workflow still requires implementation.');
    else if(action==='source-filter')toast(`${target.textContent}: no operational source corpus is connected. Sample references remain visible.`);
    else if(action==='save-note')toast('Demo review noted. No report approval or operational update was performed.');
  });
  document.addEventListener('submit',event=>{
    if(event.target.id==='new-record-form'){event.preventDefault();const form=event.target,values=new FormData(form),key=form.dataset.key,id=`DEMO-${Date.now().toString(36).toUpperCase()}`;state.records[key]=[...getRecords(key),[id,String(values.get('title')).trim(),String(values.get('owner')).trim(),'Draft']];state.details[id]=Object.fromEntries(values.entries());save();dialog.close();route();toast('Synthetic draft saved in this browser session.');}
    if(event.target.id==='scenario-action'){event.preventDefault();const values=new FormData(event.target);const action=String(values.get('action') || '').trim();if(!action)return;state.scenarioLog.push(action);save();route();}
  });
  document.addEventListener('input',event=>{
    if(event.target.id==='dor-comments'){state.dorComments=event.target.value;save();}
    if(event.target.id==='module-filter'){const query=event.target.value.toLowerCase();document.querySelectorAll('[data-module]').forEach(card=>{const module=moduleByKey(card.dataset.module);card.hidden=!`${module.name} ${module.capabilities.join(' ')}`.toLowerCase().includes(query);});}
    if(event.target.id==='record-filter'){const query=event.target.value.toLowerCase();document.querySelectorAll('#record-list tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(query));}
    if(event.target.id==='global-search'){const query=event.target.value.toLowerCase().trim(),results=document.getElementById('search-results');results.hidden=!query;results.innerHTML=query?data.modules.filter(m=>`${m.name} ${m.capabilities.join(' ')}`.toLowerCase().includes(query)).map(m=>`<a href="#${m.key}">${esc(titles[m.key] || m.name)}<small>${esc(m.capabilities[0])}</small></a>`).join('') || '<p class="empty">No modules found.</p>':'';}
  });
  window.addEventListener('hashchange',route);
  route();
})();
