[pytest]
testpaths =
    app/tests
norecursedirs =
    app/app
    .venv
    .venv_repair
    node_modules
    __pycache__
filterwarnings =
    ignore:ARC4 has been moved to cryptography\.hazmat\.decrepit\.ciphers\.algorithms\.ARC4:cryptography.utils.CryptographyDeprecationWarning
